export const worksImages = [
  {
    image_url: "./image/works/Layer 24.png",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/Layer 25.png",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/Layer 26.png",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/Layer 27.png",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/Layer 28.png",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/Layer 29.png",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/Layer 30.png",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/Layer 31.png",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/Layer 32.png",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/Layer 33.png",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/Layer 34.png",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design1.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page1.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design1.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress1.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design2.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page2.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design2.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress2.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design3.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page3.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "Creative Design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design3.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress3.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design4.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page4.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design4.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress4.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design5.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page5.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design5.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress5.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design6.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page6.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design6.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress6.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design7.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/landing-page/landing-page7.jpg",
    filter: "landing-page",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Landing Page",
  },
  {
    image_url: "./image/works/web-design/web-design7.jpg",
    filter: "web-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "web design",
  },
  {
    image_url: "./image/works/wordpress/wordpress7.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design8.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/wordpress/wordpress8.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design9.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/wordpress/wordpress9.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design10.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/wordpress/wordpress10.jpg",
    filter: "wordpress",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "wordpress",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design11.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
  {
    image_url: "./image/works/graphic-design/graphic-design12.jpg",
    filter: "graphic-design",
    main_link: "#",
    alt_url: "#",
    header: "creative design",
    description: "Graphic Design",
  },
];
